version: '3.4'

services:
  photomap_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "45432:5432"
    networks:
      - shared_photomap_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  photomap_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_photomap_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq
    

  photomap_api:
    ports:
      - "10000:8080"
    networks:
      - shared_photomap_net
    env_file:
      - env.api

  photomap_identity:
    ports:
      - "10001:8080"
    networks:
      - shared_photomap_net
    env_file:
      - env.identity
      
  photomap_worker_1:
    networks:
      - shared_photomap_net
    ports:
      - "10002:8080"
    env_file:
      - env.worker

  # photomap_worker_2:
  #   networks:
  #     - shared_photomap_net
  #   ports:
  #     - "10003:8080"
  #   env_file:
  #     - env.worker


networks:
  shared_photomap_net:
    name: photo_map
    driver: bridge